In [18]:
import pandas as pd 
import numpy as np 
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

In [4]:
data=fetch_california_housing()

In [9]:
df=pd.DataFrame(data.data,columns=data.feature_names)

In [13]:
df['Price']=data.target

In [14]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [15]:
df.shape

(20640, 9)

In [16]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

In [19]:
scaler=StandardScaler()

In [20]:
print(scaler.fit(df))

StandardScaler()

In [21]:
print(scaler.mean_)

[ 3.87067100e+00  2.86394864e+01  5.42899974e+00  1.09667515e+00
  1.42547674e+03  3.07065516e+00  3.56318614e+01 -1.19569704e+02
  2.06855817e+00]

In [25]:
x=pd.DataFrame(data.data,columns=data.feature_names)

In [26]:
x.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [27]:
y=df['Price']

In [40]:
x = (x - np.mean(x, axis=0)) / np.std(x, axis=0)

In [45]:
b=0
lr=0.00001
n=len(y)
w=np.zeros(x.shape[1])
for i in range(1000):
    y_pred=np.dot(x,w)+b
    error=y-y_pred
    dw=-2/n*np.dot(x.T,error)
    db=-2/n*np.sum(error)

    w=w-lr*dw
    b=b-lr*db

    if np.isnan(w).any() or np.isinf(w).any():
        print("Diverging! Stop training.")
        break

    if i % 100 == 0:
        loss = np.mean(error**2)
        print(f"Epoch {i}, Loss: {loss}")

Epoch 0, Loss: 5.610483198987253
Epoch 100, Loss: 5.590563704876786
Epoch 200, Loss: 5.570724604723367
Epoch 300, Loss: 5.550965569720158
Epoch 400, Loss: 5.531286272431486
Epoch 500, Loss: 5.511686386786935
Epoch 600, Loss: 5.492165588075471
Epoch 700, Loss: 5.47272355293959
Epoch 800, Loss: 5.453359959369486
Epoch 900, Loss: 5.434074486697258

In [46]:
lr=0.0003
n=len(y)
for i in range(1000):
    y_pred=np.dot(x,w)+b
    error=y-y_pred
    dw=-2/n*np.dot(x.T,error)
    db=-2/n*np.sum(error)

    w=w-lr*dw
    b=b-lr*db

    if np.isnan(w).any() or np.isinf(w).any():
        print("Diverging! Stop training.")
        break

    if i % 100 == 0:
        loss = np.mean(error**2)
        print(f"Epoch {i}, Loss: {loss}")

Epoch 0, Loss: 5.414866815591135
Epoch 100, Loss: 4.8731345147444465
Epoch 200, Loss: 4.393196369111993
Epoch 300, Loss: 3.967927529163779
Epoch 400, Loss: 3.5910363518827553
Epoch 500, Loss: 3.2569647281271026
Epoch 600, Loss: 2.960800766807007
Epoch 700, Loss: 2.6982022209702508
Epoch 800, Loss: 2.465329267336967
Epoch 900, Loss: 2.258785442801543

In [47]:
print (w)
print(b)

[ 0.3607975   0.06887611  0.05978263 -0.03131022 -0.0086062  -0.01448048
 -0.07983226 -0.04031376]
0.9559893913035774

In [48]:
mse=np.mean((y-y_pred)**2)
rmse=np.sqrt(mse)
mae=np.mean(np.abs(y-y_pred))
res = np.sum((y - y_pred)**2)
tot = np.sum((y - np.mean(y))**2)
r2 = 1 - (res / tot)

print('MSE: ',mse)
print('MAE: ',mae)
print('RMSE: ',rmse)
print('R-squared: ',r2)

MSE:  2.077291445521008
MAE:  1.121927163053081
RMSE:  1.4412811819769964
R-squared:  -0.5600548063361808